# Generated by Django 5.2.17 on 2026-09-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
